### ISSUE TITLE
Bootstrap 5 disables Dropdowns

### ISSUE THREAD

**Issue by Freshbytes** [laravel-frontend-presets/paper-dashboard#19]
The dashboard worked fine until I upgraded Bootstrap to version 5.
Dropdowns used to show the popup ".dropdown-menu" but now they don't.

I tested updating Popper, using the Bootstrap Bundle version (which is supposed to include popper), all files are loaded from the CDN as recommended.
The version of Jquery is the newest.
After a lot of testing, it seems as the dropdowns depend completely on the versions of Bootstrap and Popper included in the Dashboard.

When the dropdowns are tested with bootstrap v5 on a completely different page, they do work fine, so it is only when is used inside the paper-dashboard that doesn't work, so it seems like there is a type of conflict that I can't seem to find.

Tested in Windows 10
Chrome Version 94.0.4606.61 (Official Build) (64-bit) 
Code:

```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
```

**Comment by teamupdivision** [comment]
Hi @Freshbytes,
 
Thank you for reporting this issue and for using Creative Tim products.

Unfortunately, as the product was modified and we cannot be sure of the context and all the details of the modifications that were done on this, we are not able to give any guidance in this case. 

Please let us know if we can help with any other details and if there is anything we can help with.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @Freshbytes,
 
Hope this helped in clarifying the issue. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
